import axios from 'axios';
import { useAuthStore } from './stores/authStore';

// We'll use mock data for now, but keeping structure ready for env vars
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000/api';
const CHEF_BASE_URL = import.meta.env.VITE_CHEF_BASE_URL || 'http://localhost:5000/chef'; // Using same base for mock

export const apiClient = axios.create({
  baseURL: API_BASE_URL,
});

export const chefClient = axios.create({
  baseURL: CHEF_BASE_URL,
});

// Interceptor para añadir token JWT
apiClient.interceptors.request.use((config) => {
  const token = useAuthStore.getState().token;
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

// MOCK ADAPTERS (Because no backend)
apiClient.interceptors.response.use(
  (response) => response,
  async (error) => {
    // Mock Auth
    if (error.config.url.includes('/auth/login') && error.config.method === 'post') {
       return { 
         data: { 
           user: { id: '1', email: 'user@example.com' }, 
           token: 'mock-token' 
         } 
       };
    }
    if (error.config.url.includes('/auth/register')) {
       return { 
         data: { 
           user: { id: '1', email: 'user@example.com' }, 
           token: 'mock-token' 
         } 
       };
    }
    
    // Mock Profile
    if (error.config.url.includes('/api/profile')) {
       return { data: { success: true } };
    }
    
    // Mock Menus
    if (error.config.url.includes('/api/menus')) {
       return { 
         data: { 
           latest: [
             { id: '1', day: 'Monday', meal: 'Lunch', recipeName: 'Mock Salad', description: 'Healthy greens' },
             { id: '2', day: 'Monday', meal: 'Dinner', recipeName: 'Mock Steak', description: 'Juicy meat' }
           ] 
         } 
       };
    }

    return Promise.reject(error);
  }
);

chefClient.interceptors.response.use(
  (response) => response,
  async (error) => {
     if (error.config.url.includes('/menu/generate')) {
        return {
          data: {
             menu: [
               { id: '1', day: 'Monday', meal: 'Lunch', recipeName: 'AI Salad', description: 'Generated by Chef' },
             ],
             summary: { total_cost_eur: 45 },
             shopping_list: {
                total_items: 10,
                estimated_cost_eur: 45,
                items: [{ name: 'Lettuce' }, { name: 'Tomato' }]
             }
          }
        };
     }
     return Promise.reject(error);
  }
);


// Auth API
export const authAPI = {
  register: (email: string, password: string) =>
    apiClient.post('/auth/register', { email, password }),
  login: (email: string, password: string) =>
    apiClient.post('/auth/login', { email, password }),
};

// Profile API
export const profileAPI = {
  get: () => apiClient.get('/profile'),
  update: (data: any) => apiClient.put('/profile', data),
};

// Menu API
export const menuAPI = {
  generate: (profile: any, days: number) => 
    chefClient.post('/menu/generate', { 
      user_id: useAuthStore.getState().user?.id,
      profile, 
      days 
    }),
  save: (menuData: any) => apiClient.post('/menus', menuData),
  getLatest: () => apiClient.get('/menus/latest'),
  getHistory: () => apiClient.get('/menus/history'),
};

// Shopping API
export const shoppingAPI = {
  save: (data: any) => apiClient.post('/shopping', data),
  getLatest: () => apiClient.get('/shopping/latest'),
};

// Achievements API
export const achievementsAPI = {
  getAll: () => apiClient.get('/achievements'),
  getUserAchievements: () => apiClient.get('/achievements/user'),
};

// Stats API
export const statsAPI = {
  get: () => apiClient.get('/stats'),
};
